# acquition function optimization configuration file
run_name: bingxu_g9_opt_no_val_acqf_gamma1

outdir: /home/jgershon/projects/itopt/bingxu/round_2
surrogate_ckpt: /home/jgershon/git/cleo/ckpt/bingxu_g9_opt_no_val/bingxu_g9_opt_no_val.2025-09-19-09-38-06

opt_loop:
  N: 12
  q: 384
  fragment_dictionary: /home/jgershon/projects/itopt/bingxu/g9_fragment_dict.json
  num_iter: 25000
  lr: 0.01

acqf:
  model_batch_size: 1024
  gamma: 1
  eps: 1e-8
