defaults:
  - af3_inference@af3 
  
run_name: test_af3_winAS # name for the run
output_dir: /home/ssalike/Projects/itopt/policy_mpnn/opt_1/
pdb: /projects/ml/itopt/policy_mpnn/data/pd_input_make2.pdb # winAS
batch_size: 16
N_steps: 500
lr: 1e-4
checkpoint_every_n_steps: 10
eval: false
checkpoint_path: null

# -- MPNN params --
model_type: ligand_mpnn # protein_mpnn or ligand_mpnn
temperature: 1.0
omit_AA: CX
fixed_residues: "A142 A17 A37 A99"


reward:
  _target_: reward_utils.af3_reward
  output_dir: ${output_dir}
  af3_config: ${af3}
  metric_name: "acyl_rmsd_full_motif_best"  # Column name to use for reward
  lower_threshold: 0.1  # Values below this get reward 1.0
  upper_threshold: 10  # Values above this get reward 0.0

test_seq_list: "/home/ssalike/Projects/acyl_transferase_SM/penicillin/trash/af3_standalone/testseqs.list"