run_name: bingxu_g9_opt_no_val
model_base_path: /home/jgershon/git/cleo/ckpt/bingxu_g9_opt_no_val/bingxu_g9_opt_no_val.2025-09-19-09-38-06
outdir: /home/jgershon/projects/itopt/bingxu/round_2
fragment_dictionary: /home/jgershon/projects/itopt/bingxu/g9_fragment_dict.json
batch_size: 256
ckpt_name: "last.ckpt"
top_k: 1e5