defaults:
  - super_base
run_name: 'train_super_esm'
data:
  dataset_cfg:
    input_type: 'embedding' # embedding, sequence, or fragment
    input_shape: 'BLD' # BLD (keep seq length dim) or BD (flatten seq length dim)
    path_to_embeddings: '/projects/ml/itopt/datasets/esm_embeddings'
    embedding_key: null # use:  null for ESM   |   h_V for mpnn
model:
  base_model:
    model_type: 'conv1d' # conv1d, mlp
    input_dim: 1280