debug: false
run_name: 'conv_config_test'
trainer:
  max_epochs: 50
  log_every_n_steps: 50
  check_val_every_n_epoch: 1
checkpointer:
  monitor: 'val/pearsonr'
  mode: 'max'
data:
  dataset: 'data/trpB_arnold/four-site_clean_simplified_AA_data_2k_train_enriched_test.csv'
  test_dataset: 'data/trpB_arnold/four-site_clean_simplified_AA_data.csv'
  train_batch_size: 10
  val_batch_size: 32
  test_batch_size: 320
  num_workers: 1
  validation_mode: label # random, top-k, label, or null
  val_label: val
  val_size: 0.1
  seed: 123
  dataset_cfg:
    input_type: 'embedding' # embedding, sequence, or fragment
    label_col: 'znorm_fitness'
    name_col: 'frag_names'
    seq_col: 'AAs'
    input_shape: 'BLD'
    split_fragments_on: ':'
    path_connecting_variable: '-'
    num_fragments_in_subfolder: 2
    num_fragments: 4
    fragment_csv: 'data/trpB_arnold/four-site_fragments.csv'
    path_to_embeddings: '/projects/ml/itopt/datasets/trpB_mpnn_embeddings'
    embedding_key: 'h_V_4pos'
model:
  lr: 1e-4
  num_models: 10
  split_batch_mode: true # if true, batch size for each model will be B//N
  base_model:
    model_type: 'conv1d' # conv1d, mlp
    input_dim: 128
    hidden_dim: 64
    output_dim: 1
    p_drop: 0.2
    kernel_size: 1
    predict_variance: true # if true, predict variance
    variance_transform: "softplus" # softplus, sigmoid, clamp
    variance_scale: 1.0
  loss:
    loss_fn: 'nll' # mle, nll
test_only:
  enabled: false
  checkpoint_path: null
