run_name: atp_test # name for the run
output_dir: /home/jgershon/projects/itopt/policy_mpnn
pdb: /projects/ml/itopt/policy_mpnn/benchmarks/atp_binder/sym3_50aa_44_refined_0_suplig_FR0_0_FR1_0_FR2_0_FR3_0_FR4_2w5i_0.pdb

batch_size: 64
N_steps: 500
lr: 1e-4 # learning rate slowed for protease
checkpoint_every_n_steps: 10
eval: false
checkpoint_path: null
algorithm: dapo

# -- DAPO params --
N_updates: 16 # number of rollouts per step
update_batch_size: 8 # number of rollouts to use for each update
clip_eps_low: 0.2 # lower bound for clipping value taken from paper
clip_eps_high: 0.28 # upper bound for clipping value taken from paper

# -- MPNN params --
model_type: ligand_mpnn # protein_mpnn or ligand_mpnn
temperature: 1.0 # lower temp
omit_AA: CX

fixed_residues: A1 A2 A3 A4 A5 A6 A7 A8 A9 A12 A15 A16 A18 A19 A22 A23 A24 A25 A26 A27 A28 A29 A30 A31 A32 A34 A35 A42 A45 A46 A47 A48 A49 A50 A51 A52 A53 A54 A55 A56 A57 A58 A59 A61 A62 A66 A69 A70 A72 A73 A74 A75 A76 A77 A78 A81 A89 A92 A93 A95 A96 A97 A98 A99 A100 A101 A102 A103 A104 A105 A106 A107 A108 A109 A110 A111 A112 A114 A115 A125 A126 A127 A128 A129 A131 A132 A135 A136 A138 A139 A141 A142 A143 A144 A145 A146 A147 A148 A149 A150

reward:
  _target_: reward_utils.ATPBinder
  pipeline_config_path: /projects/ml/itopt/policy_mpnn/software/pipelines/pipelines/configs/reward_atp_binder.yaml
  output_dir: ${output_dir}
  run_name: ${run_name} # name for the run
  iptm_lb: 0.
  iptm_ub: 0.9
  hbond_lb: 0
  hbond_ub: 15
