run_name: heme_dapo_fragmented_BigBatch # name for the run
output_dir: /home/jgershon/projects/itopt/policy_mpnn
pdb: /projects/ml/itopt/policy_mpnn/benchmarks/heme_enzyme/elliot_design.pdb
batch_size: 32
N_steps: 500
lr: 1e-4
checkpoint_every_n_steps: 10
eval: false
checkpoint_path: null
algorithm: dapo

# -- DAPO params --
N_updates: 32 # number of rollouts per step
update_batch_size: 8 # number of rollouts to use for each update
clip_eps_low: 0.2 # lower bound for clipping value taken from paper
clip_eps_high: 0.28 # upper bound for clipping value taken from paper

# -- MPNN params --
model_type: protein_mpnn # protein_mpnn or ligand_mpnn
temperature: 1.0
omit_AA: CX
fixed_residues: "A50 A69 A72 A121 A229 A232"


reward:
  _target_: reward_utils.AF3RMSDPipelineReward
  pipeline_config_path: /projects/ml/itopt/policy_mpnn/software/pipelines/pipelines/configs/reward_elliot_heme_enzyme.yaml
  output_dir: ${output_dir}
  run_name: ${run_name}
  rmsd_ub: 10.0
  rmsd_lb: 0.0
  frag_cfg:
    fragment_bounds: [[0,24],[25,49],[50,74],[75,99],[100,124],[125,149],[150,174],[175,199],[200,224],[225,251]]
    sample_size: 128
    min_sample: 2