run_name: penicillin_vanilla_pg_fragmented # name for the run
output_dir: /home/jgershon/projects/itopt/policy_mpnn/penicillin_vanilla_pg_fragmented
pdb: /projects/ml/itopt/policy_mpnn/benchmarks/penicillin_enzyme/pd_input_make2.pdb # winAS
batch_size: 16
N_steps: 500
lr: 1e-4
checkpoint_every_n_steps: 10
eval: false
checkpoint_path: null
algorithm: vanillaPG

# -- MPNN params --
model_type: ligand_mpnn # protein_mpnn or ligand_mpnn
temperature: 1.0
omit_AA: CX
fixed_residues: "A142 A17 A37 A99"


reward:
  _target_: reward_utils.AF3RMSDPipelineReward 
  pipeline_config_path: /projects/ml/itopt/policy_mpnn/software/pipelines/pipelines/configs/reward_saman_penicillin.yaml
  output_dir: ${output_dir}
  rmsd_ub: 10.0
  rmsd_lb: 0.0
  frag_cfg:
    fragment_bounds: [[0,29],[30,66],[67,102],[103,130],[131,157]]
    sample_size: 64
    min_sample: 2

