run_name: petase_new_expdataW5_seqW5_exp_bounds.run1 # name for the run
output_dir: /home/jgershon/projects/itopt/policy_mpnn
pdb: /projects/ml/itopt/policy_mpnn/benchmarks/petase/rd3_11_pet.pdb

batch_size: 32
N_steps: 500
lr: 1e-4 # learning rate slowed for protease
checkpoint_every_n_steps: 50
evaluate_every_n_steps: 500 # dont want eval for now
eval: false
checkpoint_path: null
algorithm: dapo

use_avg_reward: false
avg_reward_window: 5 # number of steps to use for average reward

# USE KL ref
use_ref_kl: true
kl_weight: 1e-2

# -- DAPO params --
N_updates: 16 # number of rollouts per step
update_batch_size: 8 # number of rollouts to use for each update
clip_eps_low: 0.2 # lower bound for clipping value taken from paper
clip_eps_high: 0.28 # upper bound for clipping value taken from paper

# -- MPNN params --
model_type: ligand_mpnn # protein_mpnn or ligand_mpnn
temperature: 1.0 # default temperature
omit_AA: CX

fixed_residues: "A41 A42 A43 A44 A66 A85 A86 A87 A88 A107 A122 A127 A128 A129 A130 A164 A165 A166 A167" # residues to keep fixed cat res = 66, 107, 122


reward:
  _target_: reward_utils.UniversalReward
  output_dir: ${output_dir}
  run_name: ${run_name} # name for the run


  # frag_cfg:
#   fragment_bounds: [[0,41],[42,85],[86,127],[128,164],[165,208]]
#   sample_size: 128
#   min_sample: 2

  steps:

    # define pipeline for calculating metrics
    - name: af3
      target_fn: oracle_utils.af3_from_df
      cfg:
        run_dir: null # this will be set dynamically
        template_path: /projects/ml/itopt/policy_mpnn/benchmarks/petase/af3_template.json
        command: apptainer run --nv /software/containers/users/ikalvet/mlfold3/mlfold3_01.sif python /opt/alphafold3/run_alphafold.py 
        command_args: --run_data_pipeline=false --model_dir=/databases/alphafold --num_diffusion_samples=1

    - name: petase_metrics
      target_fn: petase_utils.add_petase_metrics_to_df
      cfg:
        ref_step: af3
        cat_res_ser: 66 # catalytic serine residue
        cat_res_his: 107 # catalytic histidine residue
        cat_res_asp: 122 # catalytic aspartate residue
        oxhres1: 198 # backbone oxyanion hole residue 1
        oxhres2: 67 # backbone oxyanion hole residue 2
        ester_atom_list: [["C8","O4","O5"], ["C11","O7","O6"]] # carbon, acyl oxygen, ester oxygen (multiple possible orientations)
        dihedrals: [[["A",107,"NE2"], ["A",66,"OG"], ["B",1,"C8"], ["B",1,"O5"]], [["A",107,"NE2"], ["A",66,"OG"], ["B",1,"C11"], ["B",1,"O6"]]]
        ref_str: /projects/ml/itopt/policy_mpnn/benchmarks/petase/rd3_11_pet.pdb
        ref_protein_chain_id: A
        ref_ligand_chain_id: X
        des_protein_chain_id: A
        des_ligand_chain_id: B
        ref_ligand_atom_names: ["C13","O2","C1","O1","C10","C8","C7","C9","C11","C6","C5","O4","O3","C4","C3","O6","C14","O7","C15","O8","C16","C21","C20","C17","C18","C19","C22","O9","O10","C23","C24","O11"]
        design_ligand_atom_name_orders: [
          ["C9","O5","C8","O4","C7","C6","C5","C21","C22","C4","C1","O1","O2","C2","C3","O3","C10","O6","C11","O7","C12","C20","C19","C13","C14","C15","C16","O8","O9","C17","C18","O10"],
          ["C10","O6","C11","O7","C12","C20","C19","C13","C14","C15","C16","O8","O9","C17","C18","O10","C9","O5","C8","O4","C7","C6","C5","C21","C22","C4","C1","O1","O2","C2","C3","O3"]
        ]

    - name: dist_to_ref_seqs
      target_fn: sequence_utils.compute_dist_to_ref_seqs_from_df
      cfg:
        ref_seqs:
          - MGWEEDLWLERPSGERTPVRRHHFPAKKAENGESAIANVERLIEEIEASGITFTATADRAVVVGWSLGVITGMIMHATGTDFITALRKALEIGKKVKEEDPEFMERHKKIVTDGNRAEIREDIDYWIEVIEKETGHAVDNARIFIATTVEEAVELARRAVELGHAIIHLPPYVIGEAGEAVVEVLAAAGVDVLLMGGLGSGVPVTIYQA # Top experimentally tested sequence after round 3
          - MGWEEDLWLERPSGERTPVRRHHFPAKKAENGESAIANVERLIEEIEASGITFTATADRAVVVGWSLGVITGMIMHATGTDFITALRKALEIGKKVKEEDPEFMERHKKIVTDGNRAEIREDIDYWIEVIQKETGHKVDKSRIFIAETVEEAIELARQAVELGHAIIHLPPYVIGEAGEAVVEVLAAAGVDVLLMGGLGSGVPVTIYQA # 2nd best experimentally tested sequence after round 3
          - MGWEEDLWLERPSGERTPVRRHHFPAKKAENGESAIANVERLIEEIEASGITFTATADRAVVVGWSLGVITGMIMHATGTDFITALRKALEIGKKVKEEDPEFMERHKKIVTDGNRAEIREDIDYWIEVIEKETGHAVDRSRIFIAETVEEAVELAARAVELGHAIIHLPPYVIGEAGEAVVEVLAAAGVDVLLMGGLGSGVPVTIYQA # 3rd best experimentally tested sequence after round 3
          - MGEEEELELERPSGERTPVRRHRFPARKANNIEEAVANVERLIEEIEASGITFTATADRAVVVGWSLGVITGMIMHATGTDFITALRKALEIGKKVKEEDPEFMERHKKIVTDGNRAEIREDIDYWIEVIEKETGHPVDRSRIFIAETVEEAVELAAEAVELGHAIIHAPPFLIGEAGEAIAEVLTAAGVDVLLMGGLGTGVPVTIYQA # 4th best experimentally tested sequence after round 3
          - MGWEEDLWLERPSGERTPVRRHHFPAKKAENGESAIANVERLIEEIRAAGVDFSARKPRAVVVGWSLGVITGMIMFATGTDFIEALRKALEIGKKVKEEDPEFMERHKKIVTDGNRAEIREDIDYWIEVIEKETGHPVDRSRIFIAETVEEAEELAREAVELGHAIIHLPPYVIGEAGEAVVEVLAAAGVDVLLMGGLGSGVPVTIYQA # 5th best experimentally tested sequence after round 3
          - MGEEEELELERPSGERTPVRRHRFPARKANNIEEAVANVERLIEEIEASGITFTATADRAVVVGWSLGVITGMIMHATGTDFITALRKALEIGKKVKEEDPEFMERHKKIVTDGNRAEIREDIDYWIEVIEKETGHPVDRSRIFIAETVEEAVELARRAVELGHAIIVLPPYLIGTAGEAVVQVLASAGVDVLLMGGLGSGVPVTIYRA # g20 momi, starting place

    - name: experimental_predictor
      target_fn: predictor_utils.experimental_predictor_from_df
      cfg:
        ckpt_path: /home/jgershon/git/cleo/ckpt/momi_mlp_round3_no_val/momi_mlp_round3_no_val.2025-12-25-19-36-51
        ckpt_name: last.ckpt


  reward_aggregation:

    # each metric here should reference a col that will be available in the df after running the steps above
    - metric: af3_iptm
      lower_bound: 0.0
      upper_bound: 0.8
      weight: 1.0
      mode: max # max or min or avg (avg: meaning the reward should be highest in the middle and lower towards the bounds)

    - metric: af3_ptm
      lower_bound: 0.0
      upper_bound: 0.8
      weight: 1.0
      mode: max 

    - metric: petase_metrics_acylox_oxh1bbN
      lower_bound: 6 # prev 2.5
      upper_bound: 10.0
      weight: 1.0
      mode: min 

    - metric: petase_metrics_acylox_oxh2bbN
      lower_bound: 6 # prev 2.5
      upper_bound: 10.0
      weight: 1.0
      mode: min

    - metric: petase_metrics_hisNE2_esterox
      lower_bound: 5 # prev 3.5
      upper_bound: 10.0
      weight: 1.0
      mode: min 

    - metric: petase_metrics_hisNE2_serOG
      lower_bound: 2.5
      upper_bound: 10.0
      weight: 1.0
      mode: min

    - metric: petase_metrics_his_ser_angle
      lower_bound: 20 # prev 60
      upper_bound: 90 # prev 120
      weight: 1.0
      mode: max # prev avg, but exp data says > 90 is good

    - metric: dist_to_ref_seqs_min
      lower_bound: 0
      upper_bound: 100
      weight: 5.0
      mode: min

    - metric: experimental_predictor_mu
      lower_bound: -1.0
      upper_bound: 2.0
      weight: 10.0
      mode: max