run_name: protease_dapo # name for the run
output_dir: /home/jgershon/projects/itopt/policy_mpnn
pdb: /projects/ml/itopt/policy_mpnn/benchmarks/protease/promising_24_hojae.cif
batch_size: 16
N_steps: 500
lr: 1e-5 # changed
checkpoint_every_n_steps: 10
eval: false
checkpoint_path: null
algorithm: dapo

# -- DAPO params --
N_updates: 16 # number of rollouts per step
update_batch_size: 2 # number of rollouts to use for each update
clip_eps_low: 0.2 # lower bound for clipping value taken from paper
clip_eps_high: 0.28 # upper bound for clipping value taken from paper

# -- MPNN params --
model_type: protein_mpnn # protein_mpnn or ligand_mpnn
temperature: 1.0
omit_AA: CX
fixed_residues: "A40 A43 A45 A60 A65 A100 B7 B8" # residues to keep fixed


reward:
  _target_: reward_utils.AF3RMSDPipelineReward 
  pipeline_config_path: /projects/ml/itopt/policy_mpnn/software/pipelines/pipelines/configs/reward_hojae_protease.yaml
  output_dir: ${output_dir}
  rmsd_ub: 10.0
  rmsd_lb: 0.0
  frag_cfg:
    # fragment_bounds: [[0,24],[25,49],[50,74],[75,99],[100,124],[125,149],[150,184]] # 7 fragments, diverged
    # fragment_bounds: [[0,30],[31,75],[76,117],[118,150],[150,184]] # 5 fragments, diverged
    # fragment_bounds: [[0,30],[31,78],[79,134],[135,184]] # 4 fragments, diverged
    # fragment_bounds: [[0,75],[76,120],[121,184]] # 3 fragments, 
    # fragment_bounds: [[0,99],[100,184]] # 2 fragments, 
    # fragment_bounds: [[0,2],[3,184]] # 2 fragments, CONVERGED
    fragment_bounds: [[0,32], [33,52], [53,94], [95,105], [106,133], [134, 150], [151,184]] # 7 fragments, 
    sample_size: 64
    min_sample: 2