run_name: protease_vanilla_pg_fragmented_5frag # name for the run
output_dir: /home/jgershon/projects/itopt/policy_mpnn/protease_vanilla_pg_fragmented_5frag
pdb: /projects/ml/itopt/policy_mpnn/benchmarks/protease/promising_24_hojae.cif
batch_size: 16
N_steps: 500
lr: 1e-4
checkpoint_every_n_steps: 10
eval: false
checkpoint_path: null
algorithm: vanillaPG

# -- MPNN params --
model_type: protein_mpnn # protein_mpnn or ligand_mpnn
temperature: 1.0
omit_AA: CX
fixed_residues: "A40 A43 A45 A60 A65 A100 B7 B8" # residues to keep fixed


reward:
  _target_: reward_utils.AF3RMSDPipelineReward 
  pipeline_config_path: /projects/ml/itopt/policy_mpnn/software/pipelines/pipelines/configs/reward_hojae_protease.yaml
  output_dir: ${output_dir}
  rmsd_ub: 10.0
  rmsd_lb: 0.0
  frag_cfg:
    # fragment_bounds: [[0,24],[25,49],[50,74],[75,99],[100,124],[125,149],[150,184]] # 7 fragments, diverged
    fragment_bounds: [[0,30],[31,75],[76,117],[118,150],[150,184]] # 5 fragments, diverged
    sample_size: 64
    min_sample: 2